const FETCH_POSTS_LOADING = 'FETCH_POSTS_LOADING';
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
const FETCH_DETAILS = 'FETCH_DETAILS';
const HANDLE_SEARCH_TERM = 'HANDLE_SEARCH_TERM';
const HANDLE_SORTING = 'HANDLE_SORTING';
const HANDLE_PERPAGE = 'HANDLE_PERPAGE';
const HANDLE_PAGE = 'HANDLE_PAGE';

export {
  FETCH_POSTS_LOADING,
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_ERROR,
  FETCH_DETAILS,
  HANDLE_SEARCH_TERM,
  HANDLE_SORTING,
  HANDLE_PERPAGE,
  HANDLE_PAGE
};
